name: Lint

on:
  pull_request:
    branches: [dev]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install Go Linters and Run
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: BACKEND
