name: Lint

on:
  pull_request:
    branches: [dev]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Check for Go files
        id: go-check
        run: echo "found=$(find . -name '*.go' | wc -l)" >> $GITHUB_OUTPUT
        working-directory: BACKEND

      - name: Install Go Linters and Run
        if: steps.go-check.outputs.found != '0'
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: BACKEND
